import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "iWatch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} `}>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
